# ----
# Site

title: Chicago Public Library Maker Lab
url: "https://orange-ape.cloudvent.net/"
baseurl:
google_analytics_key:
disqus_shortname:
newsletter_action:

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /assets/images/logo.png
description: Chicago Public Library Maker Lab
author:
  name: CPL Maker Lab
  email: makerspace@chipublib.org
  twitter: cplmakerlab
social:
  name: CPL Maker Lab
  links:
    - http://chipublib.org/maker-lab

# -----
# Build 

timezone: Etc/UTC

permalink: /:title

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
#  - jekyll-extract-element
#  - jekyll-archives

# This plugin is not available for Github Pages :-/
# jekyll-archives:
#  enabled: ['categories']

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

# Collections are like custom content types.
# - site_pages is a custom collection for organzing pages like home, about, and listing pages. Folder: _site_pages
# - guides is a custom collection. Folder: _guides
# - posts is a default Jekyll collection used for blog posts. Folder: _posts
# - pages is a default Jekyll collection that scans the root directory for any loose or standalone pages, such as 404.html.
# The reason we are using site_pages instead of default pages is for better organization, and to allow for creating new pages within the CloudCannon Admin UI.
collections:
  site_pages:
    output: true
    permalink: /:path
    _singular_name: Page 
  guides:
    output: true
    permalink: /guide/:path/
    _singular_name: Guide
  slidedecks:
    output: true
    permalink: /slidedeck/:path 
    _singular_name: Slide Deck
    _hide_content: true
  


defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      type: "posts"
    values:
      layout: "blog"
      permalink: /blog/:path
      comments: false
  -
    scope:
      type: "site_pages"
    values:
      layout: "page"      
  -
    scope:
      type: "guides"
    values:
      layout: "guide"
  - scope:
      type: "slidedecks"
    values:
      layout: "slidedeck"
      _options:
        content_markdown:
          format: p h2 h3 h4
          bold: true
          italic: true
          link: true    
          image: true
          removeformat: true
          blockquote: true
          numberedlist: true
          bulletedlist: true
          horizontalrule: true
          code: true
          table: true
          embed: true


# @@DEPRECATED in favor of Categories.
# Topics used to organize guides. 
# Each guide in the collection is assigned a single topic from a dropdown list.
# Here we define the option for "topics:" (plural) but in the guide frontmatter we use "topic:" (singular form)
# The reason is because Cloudcannon convention shows a multiselect dropdown for "topics:" but only a single select dropdown for "topic:".
# See: https://docs.cloudcannon.com/editing/interfaces/inputs/#general-inputs/select
# @@TODO find out if this is also a Jekyll/Ruby convention...
# topics:
#  - 2D design
#  - 3D design
#  - 3D printing  
#  - Coding
#  - Digital security
#  - Electronic cutter
#  - Electronics
#  - Craftsupl
#  - Lasercutting
#  - CNC Milling
#  - Sewing

# In front matter, use difficulty: (singular form).
difficulties:
  Easy: 1 - Easy
  Medium: 2 - Medium
  Hard: 3 - Hard

# Slide deck (reveal.js themes)
# For makerlab theme: assets/css/components/slidedeck.css
# The rest of the themes are in: assets/js/revealjs/dist/theme/
slide_themes:
  - makerlab
  - black
  - white
  - league
  - beige
  - sky
  - night
  - serif
  - simple
  - solarized
  - blood
  - moon

# -----------
# CloudCannon

uploads_dir: "uploads/:title"

# Complex array structures
# See: https://docs.cloudcannon.com/editing/options/input-options/#array-structures
_array_structures:
  slides:
    - label: Slide
      icon: collections
      value:
        title:
        content_markdown:
        background_color:
        background_image:
        background_size:
          - cover
          - contain

# CloudCannon Explore UI Settings
_explore:
  groups:
    - heading: Blogging
      collections:
        - posts
        - drafts      
    - heading: Pages
      collections:
        - site_pages
    - heading: How-To Guides
      collections:
        - guides   
    - heading: Slide Decks
      collections:
        - slidedecks             
    - heading: Site Settings
      collections:
        - data

# CloudCannon Content Editor 
_options:
  content: # Content Editor and block Editable Regions
    format: p h2 h3 h4
    bold: true
    italic: true
    link: true    
    image: true
    removeformat: true
    blockquote: true
    numberedlist: true
    bulletedlist: true
    horizontalrule: true
    code: true
    table: true
    embed: true
    uploads_dir: "uploads/:title"

# CloudCannon Source Editor
_source_editor:   
  tab_size: 2
  

# Footer Icons
social_icons:
  - Facebook
  - Instagram
  - LinkedIn
  - Pinterest
  - Tumblr
  - Twitter
  - YouTube
  - Email
  - RSS
  - Github